swagger: '2.0'
info:
  description: The HL7 Health Services Platform Marketplace (HSPM or Marketplace) specification is a REST API for publication, cataloging, discovering, and deployment of services and executable knowledge into any compliant IT environment in an automated manner. It is similar to an app marketplace for health services in that it manages deployment to a users local infrastructural environment and data context. It is not a flat directory of SMART-on-FHIR and other UI-only applications, but MAY be us[...]
  version: 1.0.0
  title: Health Services Platform Marketplace
  termsOfService: http://hspc/terms/
  contact:
    email: hspmTeam@hspc.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: hspc.org
basePath: /hspm
tags:
- name: licenses
  description: Licenses are globally declared terms of use, and MAY or MAY NOT be useful in all contexts. As discussed in , this is expected to be customized to the local sales and business model. Implementors and operators only focused on F/OSS Services may be satisfied by the barebones model.
- name: services
  description: A Service is a structured declaration of capabilities for a package of executable or consumable content, with release managed in a discrete lifecycle. A CDS Hooks or FHIR Terminology service “ExampleService” developed by vendor “ExampleSoft”, for example, would be declared to a Marketplace instance prior to actual release of the software to establish descriptive text, create screenshots, set standards-related declarations, and other fields.
- name: interfaces
  description: interfaces
- name: users
  description: Operations about user
- name: identity_providers
  description: Operations about identity_providers
- name: roles
  description: Operations about roles
- name: sessions
  description: Operations about sessions
schemes:
- https
- http
paths:
  /licenses:
    post:
      tags:
      - licenses
      summary: Add a new license to the marketplace
      description: ''
      operationId: addLicense
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /licenses/{id}:
    get:
      tags:
      - licenses
      summary: Returns license by Id
      description: ''
      operationId: getLicense
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - licenses
      summary: Updates license by Id
      description: ''
      operationId: updateLicense
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - licenses
      summary: Deletes a license by Id
      description: ''
      operationId: deleteLicense
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services:
    post:
      tags:
      - services
      summary: Add a new service to the marketplace
      description: ''
      operationId: addService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services/{id}:
    get:
      tags:
      - services
      summary: Returns services by Id
      description: ''
      operationId: getService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - services
      summary: Updates services by Id
      description: ''
      operationId: updateService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - services
      summary: Deletes a services by Id
      description: ''
      operationId: deleteService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services/{id}/publish:
    post:
      tags:
      - services
      summary: Returns services by Id
      description: ''
      operationId: publishService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services/{id}/unpublish:
    post:
      tags:
      - services
      summary: Returns services by Id
      description: ''
      operationId: unpublishService
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services/{serviceId}/builds:
    post:
      tags:
      - services
      summary: Add a new build to the marketplace
      description: ''
      operationId: addBuild
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /services/{serviceId}/builds/{buildId}:
    get:
      tags:
      - services
      summary: Returns services by Id
      description: ''
      operationId: getBuild
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - services
      summary: Updates services by Id
      description: ''
      operationId: updateBuild
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - services
      summary: Deletes a services by Id
      description: ''
      operationId: deleteBuild
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /interfaces:
    post:
      tags:
      - interfaces
      summary: Add a new license to the marketplace
      description: ''
      operationId: addInterface
      security:
      - interfacestore_auth:
        - write:interfaces
        - read:interfaces
  /interfaces/{id}:
    get:
      tags:
      - interfaces
      summary: Returns license by Id
      description: ''
      operationId: getInterface
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - interfaces
      summary: Updates license by Id
      description: ''
      operationId: updateInterface
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - interfaces
      summary: Deletes a license by Id
      description: ''
      operationId: deleteInterface
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /users:
    post:
      tags:
      - users
      summary: Add a new license to the marketplace
      description: ''
      operationId: addUser
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /users/{id}:
    get:
      tags:
      - users
      summary: Returns license by Id
      description: ''
      operationId: getUser
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - users
      summary: Updates license by Id
      description: ''
      operationId: updateUser
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - users
      summary: Deletes a license by Id
      description: ''
      operationId: deleteUser
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /users/{userId}/identities:
    get:
      tags:
      - users
      summary: get user identities
      description: ''
      operationId: getUserIdentities
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /groups:
    post:
      tags:
      - groups
      summary: Add a new license to the marketplace
      description: ''
      operationId: addGroup
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /groups/{id}:
    get:
      tags:
      - groups
      summary: Returns license by Id
      description: ''
      operationId: getGroup
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - groups
      summary: Updates license by Id
      description: ''
      operationId: updateGroup
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - groups
      summary: Deletes a license by Id
      description: ''
      operationId: deleteGroup
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /roles:
    post:
      tags:
      - roles
      summary: Add a new license to the marketplace
      description: ''
      operationId: addRole
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
  /roles/{id}:
    get:
      tags:
      - roles
      summary: Returns license by Id
      description: ''
      operationId: getRole
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    put:
      tags:
      - roles
      summary: Updates license by Id
      description: ''
      operationId: updateRole
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
    delete:
      tags:
      - roles
      summary: Deletes a license by Id
      description: ''
      operationId: deleteRole
      security:
      - licensestore_auth:
        - write:licenses
        - read:licenses
securityDefinitions:
  licensestore_auth:
    type: oauth2
    authorizationUrl: https://licensestore.swagger.io/oauth/authorize
    flow: implicit
    scopes:
      write:licenses: modify licenses in your account
      read:licenses: read your licenses
  interfacestore_auth:
    type: oauth2
    authorizationUrl: https://interfacestore.swagger.io/oauth/authorize
    flow: implicit
    scopes:
      write:interfaces: modify interfaces in your account
      read:interfaces: read your interfaces
  api_key:
    type: apiKey
    name: api_key
    in: header